### ISSUE TITLE
Stripped characters from data in barcode

### ISSUE THREAD

**Issue by mhei** [rdoeffinger/iec16022#2]
When I use the following command, I would expect the barcode to contain the full given string, but reading back the PNG, the two last characters are missing in the barcode. I tested this with my smartphone and an app and/or a standalone 2d barcode scanner.

`./iec16022 -c "UEXPLR4-CBR3A3-001-TSK 13471 3216" -f png -o test.png`

I tested other strings as well, but failed to find out what is special about the string above.

**Comment by rdoeffinger** [comment]
Thanks for the test-case.
This is fixed by ebbb6e2849464938c70e5af3934183f232d65134
What is special about the string is that it would just fit into the next lower barcode size if the last 2 characters are dropped, and the code checking the required size did that instead of choosing the next larger size.

**Comment by mhei** [comment]
Thank you very much for investigating this issue so quickly and for the fix. Will test tomorrow at work.
