### ISSUE TITLE
Windows binary does not output

### ISSUE THREAD

**Issue by chrios** [rdoeffinger/iec16022#7]
Am I missing something here? The windows binary is not outputting anything at all.  My command is:

```
FOR /F %%i IN (barcode.txt) DO iec16022.exe -s 20x20 -c %%i --ecc 200 -o %%i.png -f PNG
pause
```

I've also tried:
```
iec16022.exe -s 20x20 -c L-380-W1-1-1 --ecc 200 -o L-380-W1-1-1.png -f PNG
```

I've downloaded the binary from the releases section, the .exe file.  Is this the correct binary for windows?

I'm running Windows 7 64bit on an i7-2600 CPU.  I think i've seen that there was no testing done for 64bit, is that the case?

**Comment by rdoeffinger** [comment]
I so hate autotools. It worked when I tested it.
You won't believe what autotools does: it creates a iec16022.exe
But that is NOT the actual binary. It is a dummy binary that loads and runs the real binary in the .libs directory.
So what I uploaded is that wrapper (which also has the great feature of not even printing an error message when it fails) instead of the real binary.
My fault for failing at testing properly, but how someone could ever think this was a good idea or just a sane thing to do I'll never understand.

**Comment by rdoeffinger** [comment]
I uploaded the proper binary now. Sorry about that.

**Comment by chrios** [comment]
Thanks Rdoeffinger, i'll give it a test on my 64bit system today and update my comment with how it goes!

EDIT: EPS output with the command:

```
FOR /F %%i IN (barcode.txt) DO iec16022.exe -s 20x20 -c %%i --ecc 200 -o %%i.eps -f EPS
pause
```

Is working great now. Thanks a lot!!
