### ISSUE TITLE
Windows PNG

### ISSUE THREAD

**Issue by drn5910** [rdoeffinger/iec16022#8]
Hello,

When running the command on Windows 10, it doesn't create valid PNG files.

```
iec16022-0.2.7.exe -c 12345678 --format=png --ecc=200 --outfile=dm.png
```

However when running the command with `--format=eps` that works and correctly generates the EPS file.

I've tried several variations of the options (different text, different sizes etc.) and none created a valid PNG I was able to view in any program.

Thanks

**Comment by rdoeffinger** [comment]
The output file was by accident opened in "ascii" mode, so Windows helpfully replaced all bytes with value 10 by the 2-byte Windows line break sequence.
That of course broke the PNG files.
EPS only worked because you were lucky that the viewers didn't care about the line break sequence used in the EPS files...
New release that should fix this uploaded.

**Comment by drn5910** [comment]
Thank you for such a quick response and fix - that has resolved the issue.
